import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainMap from "./components/MainMap";
import MyCardDrawer from "./components/MyCardDrawer";
import Nav from "./components/Nav"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <main className="flex flex-row">
                    <Nav />
                    <div className="relative h-svh w-full">
                        <MainMap />
                        {children}
                    </div>

                </main>
            </body>
        </html>
    );
}
